FROM postgres:9.5.4

#
# This dockerfile is not used currently.
# However, it would be excellent to have this 
# file run the following commands, where the contents
# of the db folder are files on the host as in:
# docker run -v $(pwd):/usr/src/app ...
#

# WORKDIR /usr/src/app/db

# USER postgres

# RUN . ./scripts/create_fresh_carpool_db.sh carpool

# RUN . ./scripts/init_cp_web_role.sh carpool
