// location of db names 

const SCHEMA_NAME           = 'carpoolvote';

const DRIVER_TABLE  = 'driver';
const RIDER_TABLE   = 'rider';
const HELPER_TABLE  = 'helper';
const SUBMIT_DRIVER_FN = 'submit_new_driver';
const SUBMIT_RIDER_FN = 'submit_new_rider';
const SUBMIT_HELPER_FN = 'submit_new_helper';

const MATCH_TABLE   = 'match';

const UNMATCHED_DRIVERS_VIEW  = 'vw_unmatched_drivers';
const UNMATCHED_RIDERS_VIEW   = 'vw_unmatched_riders';

const CANCEL_RIDE_REQUEST_FUNCTION  = 'rider_cancel_ride_request($1, $2)';
const CANCEL_RIDER_MATCH_FUNCTION   = 'rider_cancel_confirmed_match($1, $2, $3, $4)';
const CANCEL_DRIVE_OFFER_FUNCTION   = 'driver_cancel_drive_offer($1, $2)';
const CANCEL_DRIVER_MATCH_FUNCTION  = 'driver_cancel_confirmed_match($1, $2, $3, $4)';

const ACCEPT_DRIVER_MATCH_FUNCTION  = 'driver_confirm_match($1, $2, $3, $4)';
const PAUSE_DRIVER_MATCH_FUNCTION   = 'driver_pause_match($1, $2)';

// self service 
const DRIVER_EXISTS_FUNCTION   = 'driver_exists($1, $2)';
const DRIVER_INFO_FUNCTION   = 'driver_info($1, $2)';

const DRIVER_PROPOSED_MATCHES_FUNCTION   = 'driver_proposed_matches($1, $2)';
const DRIVER_CONFIRMED_MATCHES_FUNCTION   = 'driver_confirmed_matches($1, $2)';

const RIDER_EXISTS_FUNCTION   = 'rider_exists($1, $2)';
const RIDER_INFO_FUNCTION   = 'rider_info($1, $2)';

const RIDER_CONFIRMED_MATCH_FUNCTION   = 'rider_confirmed_match($1, $2)';


// designed for an earlier db design
const CANCEL_RIDE_OFFER_FUNCTION  = 'cancel_drive_offer($1, $2)';
const REJECT_RIDE_FUNCTION        = 'reject_ride($1, $2)';
const CONFIRM_RIDE_FUNCTION       = 'confirm_ride($1, $2)';



// for db carpool
module.exports = {
  SCHEMA_NAME:          SCHEMA_NAME,

  UNMATCHED_DRIVERS_VIEW: UNMATCHED_DRIVERS_VIEW,
  UNMATCHED_RIDERS_VIEW: UNMATCHED_RIDERS_VIEW,

  DRIVER_TABLE: DRIVER_TABLE,
  RIDER_TABLE:  RIDER_TABLE,
  HELPER_TABLE: HELPER_TABLE,
  MATCH_TABLE:  MATCH_TABLE,

  CANCEL_RIDE_REQUEST_FUNCTION: CANCEL_RIDE_REQUEST_FUNCTION,
  CANCEL_RIDER_MATCH_FUNCTION:  CANCEL_RIDER_MATCH_FUNCTION,
  CANCEL_DRIVE_OFFER_FUNCTION:  CANCEL_DRIVE_OFFER_FUNCTION,
  CANCEL_DRIVER_MATCH_FUNCTION: CANCEL_DRIVER_MATCH_FUNCTION,

  ACCEPT_DRIVER_MATCH_FUNCTION: ACCEPT_DRIVER_MATCH_FUNCTION,
  PAUSE_DRIVER_MATCH_FUNCTION:  PAUSE_DRIVER_MATCH_FUNCTION,

  DRIVER_EXISTS_FUNCTION:   DRIVER_EXISTS_FUNCTION,
  DRIVER_INFO_FUNCTION:    DRIVER_INFO_FUNCTION,

  DRIVER_PROPOSED_MATCHES_FUNCTION: DRIVER_PROPOSED_MATCHES_FUNCTION,
  DRIVER_CONFIRMED_MATCHES_FUNCTION: DRIVER_CONFIRMED_MATCHES_FUNCTION,

  RIDER_EXISTS_FUNCTION: RIDER_EXISTS_FUNCTION,
  RIDER_INFO_FUNCTION: RIDER_INFO_FUNCTION,

  RIDER_CONFIRMED_MATCH_FUNCTION: RIDER_CONFIRMED_MATCH_FUNCTION,

  CANCEL_RIDE_OFFER_FUNCTION: CANCEL_RIDE_OFFER_FUNCTION,
  REJECT_RIDE_FUNCTION: REJECT_RIDE_FUNCTION,
  CONFIRM_RIDE_FUNCTION: CONFIRM_RIDE_FUNCTION
}
