// location of db names 
var SCHEMA_NAME = 'stage';
var SCHEMA_NOV2016_NAME = 'nov2016';
var DRIVER_TABLE = 'websubmission_driver';
var RIDER_TABLE = 'websubmission_rider';
var HELPER_TABLE = 'websubmission_helper';
var MATCH_TABLE = 'match';
var UNMATCHED_DRIVERS_VIEW = 'vw_unmatched_drivers';
var UNMATCHED_RIDERS_VIEW = 'vw_unmatched_riders';
var CANCEL_RIDE_REQUEST_FUNCTION = 'rider_cancel_ride_request($1, $2)';
var CANCEL_RIDER_MATCH_FUNCTION = 'rider_cancel_confirmed_match($1, $2, $3, $4)';
var CANCEL_DRIVE_OFFER_FUNCTION = 'driver_cancel_drive_offer($1, $2)';
var CANCEL_DRIVER_MATCH_FUNCTION = 'driver_cancel_confirmed_match($1, $2, $3, $4)';
var ACCEPT_DRIVER_MATCH_FUNCTION = 'driver_confirm_match($1, $2, $3, $4)';
var PAUSE_DRIVER_MATCH_FUNCTION = 'driver_pause_match($1, $2)';
// self service 
var DRIVER_EXISTS_FUNCTION = 'driver_exists($1, $2)';
var DRIVER_INFO_FUNCTION = 'driver_info($1, $2)';
var DRIVER_PROPOSED_MATCHES_FUNCTION = 'driver_proposed_matches($1, $2)';
var DRIVER_CONFIRMED_MATCHES_FUNCTION = 'driver_confirmed_matches($1, $2)';
var RIDER_EXISTS_FUNCTION = 'rider_exists($1, $2)';
var RIDER_INFO_FUNCTION = 'rider_info($1, $2)';
var RIDER_CONFIRMED_MATCH_FUNCTION = 'rider_confirmed_match($1, $2)';
// designed for an earlier db design
var CANCEL_RIDE_OFFER_FUNCTION = 'cancel_drive_offer($1, $2)';
var REJECT_RIDE_FUNCTION = 'reject_ride($1, $2)';
var CONFIRM_RIDE_FUNCTION = 'confirm_ride($1, $2)';
// for db carpool
module.exports = {
    SCHEMA_NAME: SCHEMA_NAME,
    SCHEMA_NOV2016_NAME: SCHEMA_NOV2016_NAME,
    UNMATCHED_DRIVERS_VIEW: UNMATCHED_DRIVERS_VIEW,
    UNMATCHED_RIDERS_VIEW: UNMATCHED_RIDERS_VIEW,
    DRIVER_TABLE: DRIVER_TABLE,
    RIDER_TABLE: RIDER_TABLE,
    HELPER_TABLE: HELPER_TABLE,
    MATCH_TABLE: MATCH_TABLE,
    CANCEL_RIDE_REQUEST_FUNCTION: CANCEL_RIDE_REQUEST_FUNCTION,
    CANCEL_RIDER_MATCH_FUNCTION: CANCEL_RIDER_MATCH_FUNCTION,
    CANCEL_DRIVE_OFFER_FUNCTION: CANCEL_DRIVE_OFFER_FUNCTION,
    CANCEL_DRIVER_MATCH_FUNCTION: CANCEL_DRIVER_MATCH_FUNCTION,
    ACCEPT_DRIVER_MATCH_FUNCTION: ACCEPT_DRIVER_MATCH_FUNCTION,
    PAUSE_DRIVER_MATCH_FUNCTION: PAUSE_DRIVER_MATCH_FUNCTION,
    DRIVER_EXISTS_FUNCTION: DRIVER_EXISTS_FUNCTION,
    DRIVER_INFO_FUNCTION: DRIVER_INFO_FUNCTION,
    DRIVER_PROPOSED_MATCHES_FUNCTION: DRIVER_PROPOSED_MATCHES_FUNCTION,
    DRIVER_CONFIRMED_MATCHES_FUNCTION: DRIVER_CONFIRMED_MATCHES_FUNCTION,
    RIDER_EXISTS_FUNCTION: RIDER_EXISTS_FUNCTION,
    RIDER_INFO_FUNCTION: RIDER_INFO_FUNCTION,
    RIDER_CONFIRMED_MATCH_FUNCTION: RIDER_CONFIRMED_MATCH_FUNCTION,
    CANCEL_RIDE_OFFER_FUNCTION: CANCEL_RIDE_OFFER_FUNCTION,
    REJECT_RIDE_FUNCTION: REJECT_RIDE_FUNCTION,
    CONFIRM_RIDE_FUNCTION: CONFIRM_RIDE_FUNCTION
};
//# sourceMappingURL=dbDefs.js.map